/* 교육과정신청 */
DROP TABLE BT_APLY 
	CASCADE CONSTRAINTS;

/* 강사정보 */
DROP TABLE BT_TCHR 
	CASCADE CONSTRAINTS;

/* 교실사진 */
DROP TABLE BT_CR_PHOT 
	CASCADE CONSTRAINTS;

/* 과정정보 */
DROP TABLE BT_CORS 
	CASCADE CONSTRAINTS;

/* 교실정보 */
DROP TABLE BT_CLS_RM 
	CASCADE CONSTRAINTS;

/* 매니저정보 */
DROP TABLE BT_MGR 
	CASCADE CONSTRAINTS;

/* 학생정보 */
DROP TABLE BT_STD 
	CASCADE CONSTRAINTS;

/* 주소정보 */
DROP TABLE BT_ADDR 
	CASCADE CONSTRAINTS;

/* 강사배정정보 */
DROP TABLE BT_TCH_CRS 
	CASCADE CONSTRAINTS;

/* 교육과정신청 */
CREATE TABLE BT_APLY (
	APL_NO INTEGER NOT NULL, /* 교육과정신청일련번호 */
	STD_NO INTEGER NOT NULL, /* 학생일련번호 */
	CRS_NO INTEGER NOT NULL, /* 과정일련번호 */
	REG_DT DATE NOT NULL, /* 신청일 */
	STAT INTEGER /* 상태 */
);

COMMENT ON TABLE BT_APLY IS '교육과정신청';

COMMENT ON COLUMN BT_APLY.APL_NO IS '교육과정신청일련번호';

COMMENT ON COLUMN BT_APLY.STD_NO IS '학생일련번호';

COMMENT ON COLUMN BT_APLY.CRS_NO IS '과정일련번호';

COMMENT ON COLUMN BT_APLY.REG_DT IS '신청일';

COMMENT ON COLUMN BT_APLY.STAT IS '상태';

CREATE UNIQUE INDEX PK_BT_APLY
	ON BT_APLY (
		APL_NO ASC
	);

CREATE UNIQUE INDEX UIX_BT_APLY
	ON BT_APLY (
		STD_NO ASC,
		CRS_NO ASC
	);

ALTER TABLE BT_APLY
	ADD
		CONSTRAINT PK_BT_APLY
		PRIMARY KEY (
			APL_NO
		);

ALTER TABLE BT_APLY
	ADD
		CONSTRAINT UK_BT_APLY
		UNIQUE (
			STD_NO,
			CRS_NO
		);

/* 강사정보 */
CREATE TABLE BT_TCHR (
	TCH_NO INTEGER NOT NULL, /* 강사일련번호 */
	TNAME VARCHAR2(40) NOT NULL, /* 강사명 */
	TEL VARCHAR2(30) NOT NULL, /* 강사전화 */
	EMAIL VARCHAR2(40), /* 강사이메일 */
	PHOT_PATH VARCHAR2(255) /* 강사사진 */
);

COMMENT ON TABLE BT_TCHR IS '강사정보';

COMMENT ON COLUMN BT_TCHR.TCH_NO IS '강사일련번호';

COMMENT ON COLUMN BT_TCHR.TNAME IS '강사명';

COMMENT ON COLUMN BT_TCHR.TEL IS '강사전화';

COMMENT ON COLUMN BT_TCHR.EMAIL IS '강사이메일';

COMMENT ON COLUMN BT_TCHR.PHOT_PATH IS '강사사진';

CREATE UNIQUE INDEX PK_BT_TCHR
	ON BT_TCHR (
		TCH_NO ASC
	);

CREATE UNIQUE INDEX UIX_BT_TCHR
	ON BT_TCHR (
		EMAIL ASC
	);

ALTER TABLE BT_TCHR
	ADD
		CONSTRAINT PK_BT_TCHR
		PRIMARY KEY (
			TCH_NO
		);

ALTER TABLE BT_TCHR
	ADD
		CONSTRAINT UK_BT_TCHR
		UNIQUE (
			EMAIL
		);

/* 교실사진 */
CREATE TABLE BT_CR_PHOT (
	CRP_NO INTEGER NOT NULL, /* 교실사진일련번호 */
	CLR_NO INTEGER NOT NULL, /* 교실일련번호 */
	PHOT_PATH VARCHAR2(255) NOT NULL /* 교실사진파일경로 */
);

COMMENT ON TABLE BT_CR_PHOT IS '교실사진';

COMMENT ON COLUMN BT_CR_PHOT.CRP_NO IS '교실사진일련번호';

COMMENT ON COLUMN BT_CR_PHOT.CLR_NO IS '교실일련번호';

COMMENT ON COLUMN BT_CR_PHOT.PHOT_PATH IS '교실사진파일경로';

CREATE UNIQUE INDEX PK_BT_CR_PHOT
	ON BT_CR_PHOT (
		CRP_NO ASC
	);

ALTER TABLE BT_CR_PHOT
	ADD
		CONSTRAINT PK_BT_CR_PHOT
		PRIMARY KEY (
			CRP_NO
		);

/* 과정정보 */
CREATE TABLE BT_CORS (
	CRS_NO INTEGER NOT NULL, /* 과정일련번호 */
	TITL VARCHAR2(255) NOT NULL, /* 과정명 */
	CONT CLOB NOT NULL, /* 내용 */
	ST_DT DATE NOT NULL, /* 시작일 */
	ED_DT DATE NOT NULL, /* 종료일 */
	HRS INTEGER NOT NULL, /* 일강의시간 */
	CAPA INTEGER NOT NULL, /* 수강인원 */
	CLR_NO INTEGER, /* 교실일련번호 */
	MGR_NO INTEGER /* 매니저일련번호 */
);

COMMENT ON TABLE BT_CORS IS '과정정보';

COMMENT ON COLUMN BT_CORS.CRS_NO IS '과정일련번호';

COMMENT ON COLUMN BT_CORS.TITL IS '과정명';

COMMENT ON COLUMN BT_CORS.CONT IS '내용';

COMMENT ON COLUMN BT_CORS.ST_DT IS '시작일';

COMMENT ON COLUMN BT_CORS.ED_DT IS '종료일';

COMMENT ON COLUMN BT_CORS.HRS IS '일강의시간';

COMMENT ON COLUMN BT_CORS.CAPA IS '수강인원';

COMMENT ON COLUMN BT_CORS.CLR_NO IS '교실일련번호';

COMMENT ON COLUMN BT_CORS.MGR_NO IS '매니저일련번호';

CREATE UNIQUE INDEX PK_BT_CORS
	ON BT_CORS (
		CRS_NO ASC
	);

CREATE INDEX IX_BT_CORS
	ON BT_CORS (
		TITL ASC
	);

ALTER TABLE BT_CORS
	ADD
		CONSTRAINT PK_BT_CORS
		PRIMARY KEY (
			CRS_NO
		);

/* 교실정보 */
CREATE TABLE BT_CLS_RM (
	CLR_NO INTEGER NOT NULL, /* 교실일련번호 */
	TITL VARCHAR2(40) NOT NULL /* 교실명 */
);

COMMENT ON TABLE BT_CLS_RM IS '교실정보';

COMMENT ON COLUMN BT_CLS_RM.CLR_NO IS '교실일련번호';

COMMENT ON COLUMN BT_CLS_RM.TITL IS '교실명';

CREATE UNIQUE INDEX PK_BT_CLS_RM
	ON BT_CLS_RM (
		CLR_NO ASC
	);

CREATE UNIQUE INDEX UIX_BT_CLS_RM
	ON BT_CLS_RM (
		TITL ASC
	);

ALTER TABLE BT_CLS_RM
	ADD
		CONSTRAINT PK_BT_CLS_RM
		PRIMARY KEY (
			CLR_NO
		);

ALTER TABLE BT_CLS_RM
	ADD
		CONSTRAINT UK_BT_CLS_RM
		UNIQUE (
			TITL
		);

/* 매니저정보 */
CREATE TABLE BT_MGR (
	MGR_NO INTEGER NOT NULL, /* 매니저일련번호 */
	MNAME VARCHAR2(40) NOT NULL, /* 매니저명 */
	TEL VARCHAR2(30) NOT NULL, /* 매니저전화 */
	EMAIL VARCHAR2(40) NOT NULL, /* 매니저이메일 */
	POSI VARCHAR2(40), /* 매니저직위 */
	FAX VARCHAR2(30) /* 매니저팩스 */
);

COMMENT ON TABLE BT_MGR IS '매니저정보';

COMMENT ON COLUMN BT_MGR.MGR_NO IS '매니저일련번호';

COMMENT ON COLUMN BT_MGR.MNAME IS '매니저명';

COMMENT ON COLUMN BT_MGR.TEL IS '매니저전화';

COMMENT ON COLUMN BT_MGR.EMAIL IS '매니저이메일';

COMMENT ON COLUMN BT_MGR.POSI IS '매니저직위';

COMMENT ON COLUMN BT_MGR.FAX IS '매니저팩스';

CREATE UNIQUE INDEX PK_BT_MGR
	ON BT_MGR (
		MGR_NO ASC
	);

CREATE UNIQUE INDEX UIX_BT_MGR
	ON BT_MGR (
		EMAIL ASC
	);

ALTER TABLE BT_MGR
	ADD
		CONSTRAINT PK_BT_MGR
		PRIMARY KEY (
			MGR_NO
		);

ALTER TABLE BT_MGR
	ADD
		CONSTRAINT UK_BT_MGR
		UNIQUE (
			EMAIL
		);

/* 학생정보 */
CREATE TABLE BT_STD (
	STD_NO INTEGER NOT NULL, /* 학생일련번호 */
	SNAME VARCHAR2(40) NOT NULL, /* 학생명 */
	TEL VARCHAR2(30) NOT NULL, /* 학생전화 */
	EMAIL VARCHAR2(40) NOT NULL, /* 학생이메일 */
	WORK CHAR(1) NOT NULL, /* 학생재직여부 */
	SCHL VARCHAR2(255), /* 학생최종학력 */
	ADR_NO INTEGER, /* 주소일련번호 */
	DET_ADR VARCHAR2(255) /* 상세주소 */
);

COMMENT ON TABLE BT_STD IS '학생정보';

COMMENT ON COLUMN BT_STD.STD_NO IS '학생일련번호';

COMMENT ON COLUMN BT_STD.SNAME IS '학생명';

COMMENT ON COLUMN BT_STD.TEL IS '학생전화';

COMMENT ON COLUMN BT_STD.EMAIL IS '학생이메일';

COMMENT ON COLUMN BT_STD.WORK IS '학생재직여부';

COMMENT ON COLUMN BT_STD.SCHL IS '학생최종학력';

COMMENT ON COLUMN BT_STD.ADR_NO IS '주소일련번호';

COMMENT ON COLUMN BT_STD.DET_ADR IS '상세주소';

CREATE UNIQUE INDEX PK_BT_STD
	ON BT_STD (
		STD_NO ASC
	);

CREATE UNIQUE INDEX UIX_BT_STD
	ON BT_STD (
		EMAIL ASC
	);

CREATE INDEX IX_BT_STD
	ON BT_STD (
		SNAME ASC
	);

ALTER TABLE BT_STD
	ADD
		CONSTRAINT PK_BT_STD
		PRIMARY KEY (
			STD_NO
		);

ALTER TABLE BT_STD
	ADD
		CONSTRAINT UK_BT_STD
		UNIQUE (
			EMAIL
		);

/* 주소정보 */
CREATE TABLE BT_ADDR (
	ADR_NO INTEGER NOT NULL, /* 주소일련번호 */
	PST_NO VARCHAR2(10) NOT NULL, /* 우편번호 */
	BAS_ADR VARCHAR2(255) NOT NULL /* 기본주소 */
);

COMMENT ON TABLE BT_ADDR IS '주소정보';

COMMENT ON COLUMN BT_ADDR.ADR_NO IS '주소일련번호';

COMMENT ON COLUMN BT_ADDR.PST_NO IS '우편번호';

COMMENT ON COLUMN BT_ADDR.BAS_ADR IS '기본주소';

CREATE UNIQUE INDEX PK_BT_ADDR
	ON BT_ADDR (
		ADR_NO ASC
	);

ALTER TABLE BT_ADDR
	ADD
		CONSTRAINT PK_BT_ADDR
		PRIMARY KEY (
			ADR_NO
		);

/* 강사배정정보 */
CREATE TABLE BT_TCH_CRS (
	CRS_NO INTEGER NOT NULL, /* 과정일련번호 */
	TCH_NO INTEGER NOT NULL /* 강사일련번호 */
);

COMMENT ON TABLE BT_TCH_CRS IS '강사배정정보';

COMMENT ON COLUMN BT_TCH_CRS.CRS_NO IS '과정일련번호';

COMMENT ON COLUMN BT_TCH_CRS.TCH_NO IS '강사일련번호';

CREATE UNIQUE INDEX PK_BT_TCH_CRS
	ON BT_TCH_CRS (
		CRS_NO ASC,
		TCH_NO ASC
	);

ALTER TABLE BT_TCH_CRS
	ADD
		CONSTRAINT PK_BT_TCH_CRS
		PRIMARY KEY (
			CRS_NO,
			TCH_NO
		);

ALTER TABLE BT_APLY
	ADD
		CONSTRAINT FK_BT_CORS_TO_BT_APLY
		FOREIGN KEY (
			CRS_NO
		)
		REFERENCES BT_CORS (
			CRS_NO
		);

ALTER TABLE BT_APLY
	ADD
		CONSTRAINT FK_BT_STD_TO_BT_APLY
		FOREIGN KEY (
			STD_NO
		)
		REFERENCES BT_STD (
			STD_NO
		);

ALTER TABLE BT_CR_PHOT
	ADD
		CONSTRAINT FK_BT_CLS_RM_TO_BT_CR_PHOT
		FOREIGN KEY (
			CLR_NO
		)
		REFERENCES BT_CLS_RM (
			CLR_NO
		);

ALTER TABLE BT_CORS
	ADD
		CONSTRAINT FK_BT_CLS_RM_TO_BT_CORS
		FOREIGN KEY (
			CLR_NO
		)
		REFERENCES BT_CLS_RM (
			CLR_NO
		);

ALTER TABLE BT_CORS
	ADD
		CONSTRAINT FK_BT_MGR_TO_BT_CORS
		FOREIGN KEY (
			MGR_NO
		)
		REFERENCES BT_MGR (
			MGR_NO
		);

ALTER TABLE BT_STD
	ADD
		CONSTRAINT FK_BT_ADDR_TO_BT_STD
		FOREIGN KEY (
			ADR_NO
		)
		REFERENCES BT_ADDR (
			ADR_NO
		);

ALTER TABLE BT_TCH_CRS
	ADD
		CONSTRAINT FK_BT_TCHR_TO_BT_TCH_CRS
		FOREIGN KEY (
			TCH_NO
		)
		REFERENCES BT_TCHR (
			TCH_NO
		);

ALTER TABLE BT_TCH_CRS
	ADD
		CONSTRAINT FK_BT_CORS_TO_BT_TCH_CRS
		FOREIGN KEY (
			CRS_NO
		)
		REFERENCES BT_CORS (
			CRS_NO
		);